Aggiunta tipo pagina per lista argomenti
italia/design-scuole-wordpress-theme pull request #329
Opened 2023-04-14 15:45 UTC by sviluppoRobyone

## Descrizione

- Aggiunto il template di pagina "Argomenti" che permette di visualizzare la lista di tutti gli argomenti abbinati ad almeno un contenuto.
- Aggiunta creazione automatica di pagina e voce di menù "Tutti gli argomenti" come previsto dai template HTML del sito scolastico durante l'attivazione del tema
- Aggiunta opzione per descrizione della sezione

Fixes #230 

## Checklist

- [ x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2023-08-23 10:42 UTC, sviluppoRobyone commented
@zetareticoli attualmente non è previsto il template Argomenti dentro https://github.com/italia/design-scuole-pagine-statiche
devo prima proporre l'aggiunta lì? 

Riporto anche un'immagine di anteprima

![image](https://github.com/italia/design-scuole-wordpress-theme/assets/13221786/1438a1e5-5842-42ec-b1ce-b4afb08ab4df)

2023-09-01 13:32 UTC, astagi requested changes
@sviluppoRobyone grazie della magnifica PR! Direi di procedere aggiungendo la pagina sul repo statico con una PR da parte vostra e il relativo css che non deve essere modificato qua dentro ma sul repo degli statici (che aggiornerà poi il tema WP), grazie!

2023-10-19 07:21 UTC, sviluppoRobyone commented
Inserita PR in design-scuole-pagine-statiche :)

2023-11-24 15:57 UTC, zetareticoli commented
> Inserita PR in design-scuole-pagine-statiche :)

Approvata e portata su `main`. Appena @astagi conclude nuovo rilascio e aggiornamento assets, possiamo procedere a chiusura anche di questa.

2023-12-14 13:17 UTC, closed without merging