Campi tempi e contatti servizio, contatti strutture, contatti indirizzi, configurazione variabili footer
italia/design-scuole-wordpress-theme pull request #367
Opened 2023-05-26 13:18 UTC by sviluppoRobyone

Miglioramento campi tempi e contatti del servizio, variabili per piè di pagina

## Descrizione

- Campo per specificare se sono presenti o assenti contatti "dedicati" per il servizio (se non sono presenti contatti dedicati vengono caricati in automatico i dati generali)
- Campo per inserire indicazioni su tempistiche servizio (testo di introduzione fasi e scadenze)
- Nuova scheda in configurazione "Dati fiscali e di contatto" con indirizzo, centralino, PEO, PEC, CF, codice meccanografico, codice IPA, CUF
- Mantenuto il campo per il testo aggiuntivo per il footer
- Aggiornata visualizzazione pubblica di servizio e piè di pagina

Fixes #366 

## Checklist

- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2023-05-26 13:18 UTC, sviluppoRobyone commented
Già testato con il tool di validazione scuole all'ultima versione

2023-07-07 12:34 UTC, astagi commented
Grazie @sviluppoRobyone sembra tutto ok, potresti indentare meglio il codice? grazie

2023-07-07 12:35 UTC, astagi requested changes

2023-07-07 12:35 UTC, astagi commented on single-servizio.php
> +            $contatti_dedicati = dsi_get_meta("contatti_dedicati");
Indentare

2023-07-10 12:04 UTC, sviluppoRobyone commented on single-servizio.php
> +            $contatti_dedicati = dsi_get_meta("contatti_dedicati");
Corretto con il nuovo commit

2023-07-11 12:18 UTC, sviluppoRobyone commented
Ho aggiunto le seguenti integrazioni sempre al fine di ridurre le ripetizioni:
- Campo per specificare se sono presenti o assenti contatti "dedicati" per la struttura (se non sono presenti contatti dedicati vengono caricati in automatico i dati generali)
- Aggiornata visualizzazione pubblica di struttura

2023-08-22 14:19 UTC, zetareticoli commented
@astagi le modifiche richieste sono state implementate?

2023-08-23 07:15 UTC, sviluppoRobyone commented
Dimenticavo di informare qui nella conversazione che ho aggiunto le seguenti integrazioni sempre al fine di ridurre le ripetizioni:
- Campo per specificare se sono presenti o assenti contatti "dedicati" per la l'indirizzo di studio (se non sono presenti contatti dedicati vengono caricati in automatico i dati generali)
- Aggiornata visualizzazione pubblica di indirizzo di studio

2023-08-23 08:14 UTC, zetareticoli commented
grazie @sviluppoRobyone , attendiamo ✅ di @astagi prima di procedere con merge

2023-08-30 14:09 UTC, zetareticoli approved these changes

2023-08-30 14:09 UTC, merged