Fix/eventi multi giorno in home e archivio
italia/design-scuole-wordpress-theme pull request #519
Opened 2023-11-07 09:28 UTC by sviluppoRobyone

## Descrizione

Attualmente le query sugli eventi non tengono conto della data di fine degli eventi, quindi se è presente un evento iniziato in un giorno passato ma che finisce in un giorno futuro questo sparisce dalla home, e nell'archivio viene messo negli eventi passati. Le modifiche effettuate dovrebbero correggere questo comportamento, e mostrare gli eventi fino alla conclusione del giorno in cui finiscono (sia in home sia in archivio).

Le nuove query inoltre tengono conto del caso in cui non sia presente una data di fine, assumendo che l'evento duri un giorno a partire dalla data di inizio.

## Checklist

- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2023-11-08 10:42 UTC, vcoopcsc commented
Ciao, la cosa è stata aggiustata con la versione 2.6.0: in home ci sono i "prossimi eventi" in modo che sia chiaro che in home ci sono i futuri.

2023-11-08 11:58 UTC, sviluppoRobyone commented
Il problema è che un evento che si sta svolgendo, è errato vederlo in archivio (almeno da esperienza sul campo con le scuole con cui collaboriamo, che vedono come un errore il fatto di non vedere evidenziati gli eventi in corso di svolgimento).

Ad esempio, "#ioleggoperché, dal 4 Novembre 2023 al 12 Novembre 2023", attualmente risulta nascosto anche già al 4 novembre, nonostante l'evento sia in parte nel futuro e quindi potenzialmente nei prossimi eventi.

2023-11-17 08:05 UTC, vcoopcsc commented
@sviluppoRobyone effettivamente hai ragione, sarebbe molto utile sistemare perché le scuole hanno bisogno di far vedere l'evento in home soprattutto il giorno che si verifica.

2023-11-23 18:29 UTC, zetareticoli approved these changes

2023-12-22 15:06 UTC, astagi commented
> @sviluppoRobyone ho testato la tua proposta di modifica che funziona, c'è però un problema che ti descrivo con un esempio. Se pubblico un evento "Z" che si verifica domani e termina tra 3 mesi perché ha all'interno diverse date (es. ciclo di incontri formativi, open day, ecc.) e pubblico un evento "X" che si verifica domani e finisce domani, il sistema domani mi farà vedere in home sempre l'evento "Z" fino a quando non si verifica l'ultimo giorno di quell'evento. La conseguenza di questo è che tutti gli altri eventi che ci sono in quei 3 mesi dell'evento "Z", come l'evento "X" non compariranno mai in home. Questo crea problemi perché la scuola può avere eventi che si verificano in giornata ed eventi che durano più mesi. La soluzione, ma dimmi che ne pensi, potrebbe essere anche quella di far comparire in home più di un evento come accade per i contenuti di tipo "Articolo".
> 
> Spero di essere stata chiara!

@sviluppoRobyone mettiamo in request change questa PR facciamo delle verifiche e delle modifiche opportune. Grazie @vcoopcsc

2023-12-22 15:07 UTC, astagi requested changes
Valutare le considerazioni di @vcoopcsc

2024-01-19 16:30 UTC, sviluppoRobyone commented
La PR #596 consente di superare il problema impostando più eventi in pagina iniziale

2024-01-23 08:18 UTC, closed without merging