Update banner.php
italia/design-scuole-wordpress-theme pull request #544
Opened 2023-11-19 15:36 UTC by SiteMastersLesto

Aggiunta rotazione banner "Pubblicità e Informazione". Questa aggiunta non va a danneggiare minimamente l'accessibilità del sito. Non viene implementato nessun tasto aggiuntivo, viene solo attivata l'auto rotazione.

## Descrizione

Aggiunta rotazione banner "Pubblicità e Informazione". 
Questa aggiunta non va a danneggiare minimamente l'accessibilità del sito. Non viene implementato nessun tasto aggiuntivo, viene solo attivata l'auto rotazione al banner.

## Checklist

- [ ] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [ x ] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2023-11-30 14:01 UTC, zetareticoli reviewed
Se si non volesse l'auto-rotazione come si torna indietro?

2023-12-05 09:17 UTC, SiteMastersLesto commented
Per fermare il banner da interfaccia utente basta andare con il cursore sopra...

2023-12-05 09:52 UTC, vcoopcsc commented
Non sono convinta che questo basti. 
Non necessariamente le persone con disabilità usano il mouse, pensa ad esempio ai ciechi che usano la navigazione tramite tastiera e o a chi ha difficoltà ad usare gli arti superiori e naviga con altre tecnologie assistive. Il fatto che basti il movimento del cursore per bloccare l'autoscorrimento deve essere poi spiegato da qualche parte e non può essere dato per scontato. Oltre al fatto che, per navigare senza vedere lo scorrimento, anche io dovrei sostare necessariamente col cursore sopra lo slideshow e non mi pare il massimo dell'usabilità. Cosa diversa è l'inserimento del tasto pausa/play che, se adeguatamente spiegato nel codice, può essere interpretato e comunicato all'utente dalle tecnologie assistive (come lo screen reader). Magari è superfluo dirlo, ma aggiungo un altro pezzo, sarebbe meglio che il tasto play/pausa abbia un livello minimo di contrasto sufficiente per essere percepito dagli utenti.

2023-12-05 10:07 UTC, zetareticoli requested changes
Va previsto un controllo accessibile anche da tastiera per navigare i banner a rotazione

2024-02-11 06:39 UTC, paolocarl commented
Buongiorno. Come si fa a mettere l'impostazione dei banner per avere la stessa dimensione delle immagini?

2024-03-25 17:16 UTC, closed without merging