Refactoring Panoramica Didattica
italia/design-scuole-wordpress-theme pull request #568
Opened 2023-12-10 17:58 UTC by rcoopcsc

Modifiche per migliorare coerenza, usabilità ed accessibilità delle informazioni 

## Descrizione
Sono stati corretti alcuni titoli, intestazioni, diciture ed elementi grafici delle card delle schede progetti e didattica
 
Fixes #563

## Checklist

- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2023-12-11 20:30 UTC, zetareticoli reviewed
Ciao @rcoopcsc, seppur siano tutte modifiche apprezzabili, prima di poterle integrare ufficialmente nel tema WordPress dovrebbero essere viste e integrate nei templates statici, che teniamo allineati come risorsa del modello. 

Pertanto, ti chiedo cortesemente di aprire la stessa PR nel [repo dedicato,](https://github.com/italia/design-scuole-pagine-statiche) così appena approviamo lì i cambiamenti, possiamo aggiornare anche Wordpress.

2023-12-12 11:44 UTC, rcoopcsc commented
Ok @zetareticoli fatta https://github.com/italia/design-scuole-pagine-statiche/pull/67

2023-12-21 16:44 UTC, zetareticoli commented
Ciao @rcoopcsc , ti ho lasciato review sul [repo statico](https://github.com/italia/design-scuole-pagine-statiche/pull/67)

2023-12-22 14:48 UTC, zetareticoli requested changes
Integrare le modifiche apportate nel repository dei templates statici.

2024-01-03 08:55 UTC, rcoopcsc commented
Ciao @zetareticoli ho fatto nuova PR per i temi statici con le correzioni qui https://github.com/italia/design-scuole-pagine-statiche/pull/70 - scusate ho cancellato la vecchia per sbaglio :-(

2024-01-05 14:25 UTC, rcoopcsc commented
Ciao @zetareticoli ho visto che avete mergiato la mia PR https://github.com/italia/design-scuole-pagine-statiche/pull/70 per le pagine statiche. Come deve proseguire questa PR adesso?

2024-01-05 14:48 UTC, zetareticoli commented
@rcoopcsc dovresti aggiornare il template allo stesso modo come hai fatto sulla versione statica. Non ci sono modifiche al CSS giusto?

2024-01-17 16:06 UTC, rcoopcsc commented
@zetareticoli ho aggiornato i files dovrebbe essere pronta

2024-01-17 16:20 UTC, zetareticoli approved these changes

2024-02-10 09:46 UTC, astagi approved these changes

2024-02-10 09:47 UTC, merged