Aggiunta opzioni per modulo login
italia/design-scuole-wordpress-theme pull request #654
Opened 2024-03-25 16:22 UTC by sviluppoRobyone

## Descrizione
- Ridenominata scheda configurazione "Servizi esterni" in "Accesso ai servizi" e inserimento area "Area riservata di Wordpress"
- Opzioni "Titolo per il modulo di login" e "Descrizione per il modulo di login" per configurare le informazioni visualizzate nella modale di accesso

Fixes #376 

## Checklist

- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2024-03-25 17:15 UTC, zetareticoli requested changes

2024-03-25 17:15 UTC, zetareticoli commented on inc/admin/options.php
> +        'desc' => __( 'Area di configurazione della sezione di accesso all\'area riservata di Wordpress, da mostrare nella maschera di login.' , 'design_scuole_italia' ),
```suggestion
        'desc' => __( 'Configurazione della sezione di accesso all\'area riservata di Wordpress.' , 'design_scuole_italia' ),
```

2024-03-25 17:15 UTC, zetareticoli commented on inc/admin/options.php
> +		'desc' => __( 'Titolo visualizzato nella sezione di accesso all\'area riservata di Wordpress, nella maschera di login (Se non compilato, viene valorizzato con "Personale scolastico")', 'design_scuo
```suggestion
		'desc' => __( 'Titolo visualizzato nella sezione di accesso all\'area riservata di Wordpress (se non compilato viene mostrato "Personale scolastico")', 'design_scuole_italia' ),
```

2024-03-25 17:15 UTC, zetareticoli commented on inc/admin/options.php
> +		'desc' => __( 'Introduzione visualizzata nella sezione di accesso all\'area riservata di Wordpress, nella maschera di login (Se non compilato, viene valorizzato con "Entra nel sito della scuola con
```suggestion
		'desc' => __( 'Introduzione visualizzata nella sezione di accesso all\'area riservata di Wordpress (se non compilato, viene mostrato "Entra nel sito della scuola con le tue credenziali per gestire contenuti, visualizzare circolari e altre funzionalità.")', 'design_scuole_italia' ),
```

2024-04-02 15:41 UTC, zetareticoli requested changes

2024-04-02 15:41 UTC, zetareticoli commented on inc/admin/options.php
> +		'desc' => __( 'Titolo visualizzato nella sezione di accesso all\'area riservata di Wordpress (se non compilato viene mostrato "Personale scolastico")', 'design_scuole_italia' ),
```suggestion
		'desc' => __( 'Titolo presente nella sezione di accesso all\'area riservata di Wordpress (se non compilato viene mostrato "Personale scolastico")', 'design_scuole_italia' ),
```

2024-04-02 15:41 UTC, zetareticoli commented on inc/admin/options.php
> +		'desc' => __( 'Introduzione visualizzata nella sezione di accesso all\'area riservata di Wordpress (se non compilato, viene mostrato "Entra nel sito della scuola con le tue credenziali per gestire
```suggestion
		'desc' => __( 'Introduzione presente nella sezione di accesso all\'area riservata di Wordpress (se non compilato, viene mostrato "Entra nel sito della scuola con le tue credenziali per gestire contenuti, visualizzare circolari e altre funzionalità.")', 'design_scuole_italia' ),
```

2024-05-03 09:58 UTC, zetareticoli commented
@sviluppoRobyone se procedete con aggiornamento possiamo pensare al merge di questa PR

2024-05-03 13:28 UTC, sviluppoRobyone commented
Proceduto, grazie!

2024-05-03 13:38 UTC, zetareticoli approved these changes

2024-05-16 09:11 UTC, astagi approved these changes

2024-05-16 09:12 UTC, merged