Aggiunta chiusura del menu mobile premendo il tasto ESC
italia/design-scuole-wordpress-theme pull request #703
Opened 2024-08-07 09:39 UTC by rcoopcsc

Aggiunta funzionalità di chiusura del menu mobile premendo il tasto ESC

## Descrizione
Fixes #702

## Checklist

- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2024-08-28 13:37 UTC, zetareticoli reviewed
@rcoopcsc per quale ragione hai messo lo script direttamente nel file `header.php` invece di aggiungerlo ad esempio a `scuole.js`?

2024-08-29 06:01 UTC, rcoopcsc commented
@zetareticoli si hai ragione, così va meglio?

2024-09-04 13:29 UTC, astagi requested changes
Modificare nel progetto Scuole pagine statiche.

2024-09-04 13:29 UTC, closed without merging

2024-09-05 05:30 UTC, rcoopcsc commented
Fatto qui https://github.com/italia/design-scuole-pagine-statiche/pull/77