Fix/accessibility 2024
italia/design-scuole-wordpress-theme pull request #713
Opened 2024-09-10 15:16 UTC by sviluppoRobyone

## Descrizione

Sono stati apportati i seguenti miglioramenti dell'accessibilità, tenendo conto delle indicazioni di WAVE, SiteImprove e Lighthouse, e di alcuni issue aperti. In particolare, sono state effettuate le seguenti modifiche:

- [x] Miglioramento della gerarchia degli header in:
  - [x] Header didattica
  - [x] Header servizi
  - [x] Barra laterale dei filtri (desktop e mobile)
  - [x] Pagine di archivio
  - [x] Pagina degli argomenti
  - [x] Pagina progetto
  - [x] Pagina organizzazione
- [x] `aria-label` coerente con il contenuto del controllo in:
  - [x] titolo della link list a sinistra delle pagine foglia
  - [x] pulsanti dei filtri su mobile
- [x] Skiplink all'interno dell'header
- [x] Il menu di navigazione per mobile viene visivamente nascosto su desktop (attualmente è solo fuori schermo), per evitare warning su controlli interattivi non focusabili da tecnologie assistive in quanto presente l'attributo `aria-hidden="true"`.
- [x] Rimosso l'attributo `aria-description` da alcuni pulsanti in quanto non ancora ufficializzato da W3C;
- [x] Specificato `alt` placeholder scheda didattica.

Sono stati poi risolti alcuni warning di PHP.

Fixes #701 #710 #708 

Nel caso le modifiche fossero approvate, siamo a disposizione per allineare la repository delle pagine statiche.

## Checklist

- [x] Le modifiche sono state verificate sui [Browser supportati](https://getbootstrap.com/docs/5.1/getting-started/browsers-devices/) e, in caso di modifiche frontend, per diverse risoluzioni dello schermo.
- [x] Sono stati effettuati controlli di accessibilità in ottemperanza a quanto descritto nell'[area "Accessibilità" delle linee guida di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/it/versione-corrente/doc/esperienza-utente/accessibilita.html).

2024-09-25 14:56 UTC, sviluppoRobyone commented
Abbiamo effettuato il revert di una modifica che andava a modificare il file scuole.js e che causava un conflitto di merge (oltre a causare un disallineamento con il javascript sorgente presente nelle pagine statiche).

2024-10-02 12:49 UTC, vcoopcsc commented
Confermo che le issue citate e anche la 709 sono risolte dalla PR

2024-10-09 09:32 UTC, Fupete reviewed
Ho aperto una nuova PR con alcuni piccoli fix rispetto al logo. Lascio ad @astagi merge e review. Grazie dell'ottimo lavoro.

2024-10-09 13:40 UTC, zetareticoli requested changes
attenzione a modifiche al file `scuole.js` in quanto questo assets proviene dal repo `design-scuole-pagine-statiche`

2024-10-09 13:53 UTC, astagi commented
> Abbiamo effettuato il revert di un commit che andava a modificare il file scuole.js e che causava un conflitto di merge (oltre a causare un disallineamento con il javascript sorgente presente nelle pagine statiche).

Grazie infinite @sviluppoRobyone e grazie anche della review da parte di @vcoopcsc e i fix ulteriori da parte di @Fupete 

@sviluppoRobyone una volta mergiate (rilasceremo il tema entro stasera) se potete contribuire anche alla parte statica di scuole sarebbe davvero fantastico! Grazie a tutti

2024-10-09 15:55 UTC, closed without merging

2024-10-09 15:55 UTC, astagi commented
Chiusa in favore di #724 by @Fupete